name: iOS Build and Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14 # 이 부분을 적절한 macOS 버전으로 설정

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/SwiftPM
            ~/Library/Caches/CocoaPods
            ~/Library/Caches/org.swift.swiftpm
            ~/.swiftpm
          key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json)
          scheme=$(echo $scheme_list | jq -r '.project.targets[0]')
          echo "Using default scheme: $scheme"
          echo "scheme=$scheme" >> $GITHUB_ENV

      - name: Build Project
        run: |
          echo "Building scheme: ${{ env.scheme }}"
          xcodebuild build-for-testing -scheme "${{ env.scheme }}" -destination "platform=iOS Simulator,name=Any available iPhone simulator"

      - name: Run Tests
        run: |
          echo "Testing scheme: ${{ env.scheme }}"
          xcodebuild test-without-building -scheme "${{ env.scheme }}" -destination "platform=iOS Simulator,name=Any available iPhone simulator"
