name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Swift Package Manager packages
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ~/.swiftpm
          key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo "Using default scheme: $default"

      - name: Build
        env:
          scheme: $(cat default)
          platform: iOS Simulator
        run: |
          max_retries=3
          count=0
          until xcodebuild build-for-testing -scheme "$scheme" -destination "platform=$platform,name=Any available iPhone simulator"; do
            count=$(($count+1))
            if [ $count -ge $max_retries ]; then
              echo "Attempt $count failed and there are no more retries left."
              exit 1
            fi
            echo "Attempt $count failed! Trying again in 15 seconds..."
            sleep 15
          done

      - name: Test
        env:
          scheme: $(cat default)
          platform: iOS Simulator
        run: |
          max_retries=3
          count=0
          until xcodebuild test-without-building -scheme "$scheme" -destination "platform=$platform,name=Any available iPhone simulator"; do
            count=$(($count+1))
            if [ $count -ge $max_retries ]; then
              echo "Attempt $count failed and there are no more retries left."
              exit 1
            fi
            echo "Attempt $count failed! Trying again in 15 seconds..."
            sleep 15
          done
